// Generated by scripts/build-offline.cjs. Cache both collections and fonts.
const VERSION = "5c8b70fc3ffb7a7d";
const CACHE_PREFIX = 'ewam-reader:' + self.registration.scope + ':';
const CACHE = CACHE_PREFIX + VERSION;
const ASSETS = [
  "app.js",
  "assets/branding/entrance-landscape.jpg",
  "assets/branding/entrance-portrait.jpg",
  "assets/branding/icon-180.png",
  "assets/branding/icon-192.png",
  "assets/branding/icon-32.png",
  "assets/branding/icon-512.png",
  "assets/branding/icon-maskable-512.png",
  "assets/branding/icon-source.jpg",
  "assets/fonts/EB-Garamond-OFL.txt",
  "assets/fonts/EB-Garamond-italic-0.woff2",
  "assets/fonts/EB-Garamond-italic-1.woff2",
  "assets/fonts/EB-Garamond-italic-2.woff2",
  "assets/fonts/EB-Garamond-italic-3.woff2",
  "assets/fonts/EB-Garamond-italic-4.woff2",
  "assets/fonts/EB-Garamond-italic-5.woff2",
  "assets/fonts/EB-Garamond-italic-6.woff2",
  "assets/fonts/EB-Garamond-normal-10.woff2",
  "assets/fonts/EB-Garamond-normal-11.woff2",
  "assets/fonts/EB-Garamond-normal-12.woff2",
  "assets/fonts/EB-Garamond-normal-13.woff2",
  "assets/fonts/EB-Garamond-normal-7.woff2",
  "assets/fonts/EB-Garamond-normal-8.woff2",
  "assets/fonts/EB-Garamond-normal-9.woff2",
  "assets/fonts/Inter-OFL.txt",
  "assets/fonts/Inter-normal-14.woff2",
  "assets/fonts/Inter-normal-15.woff2",
  "assets/fonts/Inter-normal-16.woff2",
  "assets/fonts/Inter-normal-17.woff2",
  "assets/fonts/Inter-normal-18.woff2",
  "assets/fonts/Inter-normal-19.woff2",
  "assets/fonts/Inter-normal-20.woff2",
  "assets/fonts/Jomolhari-OFL.txt",
  "assets/fonts/Jomolhari-normal-21.woff2",
  "assets/fonts/Jomolhari-normal-22.woff2",
  "assets/fonts/fonts.css",
  "collections.css",
  "collections.js",
  "content/ewam.js",
  "content/prayers.js",
  "gestures.js",
  "index.html",
  "manifest.webmanifest"
];
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS.map(asset =>
    new Request(new URL(asset, self.registration.scope), {cache:'reload'})))));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys
    .filter(key => key.startsWith(CACHE_PREFIX) && key !== CACHE).map(key => caches.delete(key))))
    .then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || !url.href.startsWith(self.registration.scope)) return;
  event.respondWith(caches.open(CACHE).then(async cache => {
    const cached = event.request.mode === 'navigate' ?
      await cache.match(new URL('index.html', self.registration.scope)) : await cache.match(event.request);
    return cached || fetch(event.request);
  }));
});
// Wait for old readers to close before activation: an open page keeps a
// coherent edition instead of mixing new content with older application code.
