// Generate a versioned precache from the files actually shipped by GitHub Pages.
// Run after editing application code, content, branding or fonts.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');
function files(dir) {
  return fs.readdirSync(path.join(root, dir), {withFileTypes:true})
    .flatMap(entry => entry.isDirectory() ? files(dir + '/' + entry.name) : [dir + '/' + entry.name]);
}
const assets = ['index.html','app.js','collections.js','collections.css','manifest.webmanifest',
  'content/ewam.js','content/prayers.js', ...files('assets/fonts'), ...files('assets/branding')].sort();
const hash = crypto.createHash('sha256');
for (const file of assets) hash.update(file).update(fs.readFileSync(path.join(root, file)));
const version = hash.digest('hex').slice(0,16);
const worker = `// Generated by scripts/build-offline.cjs. Cache both collections and fonts.
const VERSION = ${JSON.stringify(version)};
const CACHE_PREFIX = 'ewam-reader:' + self.registration.scope + ':';
const CACHE = CACHE_PREFIX + VERSION;
const ASSETS = ${JSON.stringify(assets,null,2)};
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS.map(asset =>
    new Request(new URL(asset, self.registration.scope), {cache:'reload'})))));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys
    .filter(key => key.startsWith(CACHE_PREFIX) && key !== CACHE).map(key => caches.delete(key))))
    .then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || !url.href.startsWith(self.registration.scope)) return;
  event.respondWith(caches.open(CACHE).then(async cache => {
    const cached = event.request.mode === 'navigate' ?
      await cache.match(new URL('index.html', self.registration.scope)) : await cache.match(event.request);
    return cached || fetch(event.request);
  }));
});
// Wait for old readers to close before activation: an open page keeps a
// coherent edition instead of mixing new content with older application code.
`;
fs.writeFileSync(path.join(root, 'sw.js'), worker);
console.log('Offline version:', version, 'assets:', assets.length);
