"""Import the corrected prayer body without changing its characters.

Usage: python3 scripts/import-prayers.py /path/to/corrected-v3.docx
Front matter is omitted at the first chapter boundary. Source paragraph IDs
remain stable so front matter and translations can be added later.
"""
from pathlib import Path
from zipfile import ZipFile
import argparse
import hashlib
import json
import xml.etree.ElementTree as ET

TITLE = '༄༅། ། སྒང་སྟེང་གསང་སྔགས་ཆོས་གླིང་ཉེར་མཁོའི་ཆོས་སྤྱོད་བཞུགས་སོ། །'
BOUNDARY = '༼ཚོམ་བུ་དང་པོ་སྐྱབས་སེམས་ཀྱི་རིམ་པ། ༽'
NS = {'w': 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'}
W = '{' + NS['w'] + '}'


def run_text(run):
    return ''.join((x.text or '') if x.tag == W + 't' else
                   '\t' if x.tag == W + 'tab' else
                   '\n' if x.tag == W + 'br' else '' for x in run)


def paragraph_text(p):
    return ''.join(run_text(r) for r in p.findall('./w:r', NS))


def import_book(source):
    with ZipFile(source) as z:
        document = ET.fromstring(z.read('word/document.xml'))
    paragraphs = document.findall('./w:body/w:p', NS)
    start = next(i for i, p in enumerate(paragraphs) if paragraph_text(p) == BOUNDARY)
    sections, pending, group = [], [], ''
    for i, p in enumerate(paragraphs[start:], start):
        text = paragraph_text(p)
        style = p.find('./w:pPr/w:pStyle', NS)
        style = style.get(W + 'val') if style is not None else 'Normal'
        heading = int(style[-1]) if style in ('Heading1', 'Heading2') else 0
        runs = []
        for r in p.findall('./w:r', NS):
            chunk = run_text(r)
            if not chunk:
                continue
            run, properties = {'text': chunk}, r.find('./w:rPr', NS)
            if properties is not None:
                for prop, key in [('b', 'bold'), ('i', 'italic'), ('u', 'underline')]:
                    el = properties.find('w:' + prop, NS)
                    if el is not None and el.get(W + 'val', '1') not in ('0', 'false', 'none'):
                        run[key] = True
                size = properties.find('./w:sz', NS)
                if not heading and size is not None:
                    scale = round(float(size.get(W + 'val')) / 34, 6)
                    if abs(scale - 1) > .005:
                        run['scale'] = scale
            if runs and {k: v for k, v in runs[-1].items() if k != 'text'} == {k: v for k, v in run.items() if k != 'text'}:
                runs[-1]['text'] += chunk
            else:
                runs.append(run)
        block = {'id': f'prayer-p{i:04d}', 'type': 'SOURCE', 'runs': runs,
                 'heading': heading, 'sourceStyle': style}
        align = p.find('./w:pPr/w:jc', NS)
        if align is not None and align.get(W + 'val') in ('center', 'right'):
            block['align'] = align.get(W + 'val')
        if heading == 1 and text.startswith('༼ཚོམ་བུ'):
            group = text
            pending.append(block)
            continue
        if heading == 1 or not sections:
            sections.append({'id': f'prayer-text-{i:04d}', 'title': text,
                             'group': group, 'inIndex': True, 'blocks': pending})
            pending = []
        sections[-1]['blocks'].append(block)
    if pending:
        sections[-1]['blocks'].extend(pending)
    expected = '\n'.join(paragraph_text(p) for p in paragraphs[start:])
    actual = '\n'.join(''.join(r['text'] for r in b['runs']) for s in sections for b in s['blocks'])
    assert expected == actual, 'Import changed source text or order'
    # The requested book title is shown once, before the first prayer.
    sections[0]['blocks'].insert(0, {'id': 'prayer-title', 'type': 'SOURCE',
        'heading': 1, 'runs': [{'text': TITLE}], 'sourceStyle': 'CollectionTitle'})
    metadata = {'edition': source.name, 'sha256': hashlib.sha256(source.read_bytes()).hexdigest(),
                'frontMatterParagraphs': start, 'prayerParagraphs': len(paragraphs) - start,
                'texts': len(sections)}
    return sections, metadata


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    args = parser.parse_args()
    sections, metadata = import_book(args.source)
    target = Path(__file__).resolve().parents[1] / 'content' / 'prayers.js'
    target.write_text('// Generated by scripts/import-prayers.py; prayer body only.\n' +
        'window.PRAYER_TITLE = ' + json.dumps(TITLE, ensure_ascii=False) + ';\n' +
        'window.PRAYER_SOURCE = ' + json.dumps(metadata, ensure_ascii=False) + ';\n' +
        'window.TABS_DATA.PRAYERS = ' + json.dumps(sections, ensure_ascii=False, separators=(',', ':')) + ';\n')
    print(json.dumps(metadata, ensure_ascii=False))
